name: Deploy WordPress Plugin

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  deploy:
    name: Deploy to Development Server
    runs-on: ubuntu-latest

    env:
      PLUGIN_NAME: kloudpanel

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, xml, zip

      - name: Debug SSH Connection
        run: |
          # Create SSH directory and set permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Write private key to file and debug its content
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          echo "=== Checking SSH key format ==="
          if ! grep -q "PRIVATE KEY" ~/.ssh/deploy_key; then
            echo "Error: Invalid SSH key format"
            exit 1
          fi
          
          echo "=== Testing SSH connection with verbose output ==="
          ssh -v -i ~/.ssh/deploy_key \
              -o StrictHostKeyChecking=no \
              -o ConnectTimeout=10 \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              "echo 'Connection test successful'" || {
            echo "SSH connection failed with exit code $?"
            exit 1
          }

      - name: Create plugin archive
        if: success()
        run: |
          mkdir -p build
          zip -r "build/${{ env.PLUGIN_NAME }}.zip" . -x "*.git*" "*.github*" "build*" "tests*" "*.DS_Store"

      - name: Deploy via SFTP
        if: success()
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SSH_USER }}
          server: ${{ secrets.SSH_HOST }}
          port: '22'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './*'
          remote_path: ${{ secrets.REMOTE_PATH }}/wp-content/plugins/kloudpanel/
          args: '-o StrictHostKeyChecking=no'
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            README.md
            .gitignore
            build/**
