name: Deploy WordPress Plugin

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  deploy:
    name: Deploy to Development Server
    runs-on: ubuntu-latest

    env:
      PLUGIN_NAME: kloudpanel

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, xml, zip

      - name: Create plugin archive
        run: |
          mkdir -p build
          zip -r "build/${{ env.PLUGIN_NAME }}.zip" . -x "*.git*" "*.github*" "build*" "tests*" "*.DS_Store"

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SSH_USER }}
          server: ${{ secrets.SSH_HOST }}
          port: '22'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './*'
          remote_path: ${{ secrets.REMOTE_PATH }}/wp-content/plugins/kloudpanel/
          args: '-o StrictHostKeyChecking=no'
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            README.md
            .gitignore
            build/**

      - name: Notify on success
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: '✅ Plugin successfully deployed to development server!'
            })

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: '❌ Plugin deployment failed. Please check the workflow logs.'
            })
